version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: task-manager-app
    command: bash -c "chmod -R 777 storage bootstrap/cache && php-fpm"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "5173:5173"
    depends_on:
      - mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:stable-alpine
    container_name: task-manager-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.3
    container_name: task-manager-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  dbdata:

networks:
  laravel-network:
